version: "3.8"

services:
  app:
    build:
      context: .
    container_name: task-tracker-app-prod
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb-prod
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-prod:/data/db

volumes:
  mongo-data-prod:
