version: "3.8"

services:
  app:
    build:
      context: .
    container_name: task-tracker-app-dev
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6.0
    container_name: mongodb-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-dev:/data/db

volumes:
  mongo-data-dev:
